market_research_task:
  description: >
    Conduct an in-depth analysis of the mobile phone market for 2024.
    Investigate market trends, consumer preferences, competitor strategies, 
    and potential market opportunities.
  expected_output: >
    A comprehensive market research report with:
    - Top 10 market insights
    - Consumer preference analysis
    - Competitive landscape overview
    - Emerging technology trends
    - Potential market opportunities
  agent: researcher

strategy_development_task:
  description: >
    Based on the market research, develop a comprehensive marketing strategy 
    for the mobile phone brand. Identify target segments, positioning, 
    and key marketing initiatives.
  expected_output: >
    A detailed marketing strategy document including:
    - Target market segments
    - Unique value proposition
    - Marketing channel strategy
    - Key messaging and positioning
    - Proposed marketing campaigns
  agent: marketing_strategist

product_positioning_task:
  description: >
    Develop a detailed product positioning strategy that highlights 
    the unique features and benefits of the mobile phone brand.
    Create a compelling narrative that differentiates the product 
    in the competitive mobile phone market.
  expected_output: >
    A comprehensive product positioning document with:
    - Detailed value proposition
    - Competitive differentiation strategy
    - Brand storytelling framework
    - Key selling points and unique features
  agent: product_positioning_expert